#!/bin/bash


# installer log is not writable, use for reference only.
INST_LOG="/var/log/apps/${TRIM_APPNAME}.log"

# Optional FWPORTS file
FWPORTS_FILE="/var/apps/${TRIM_APPNAME}/etc/${TRIM_APPNAME}.sc"

# Temporary directory when the package is upgrading
TMP_DIR="${TRIM_TEMP_UPGRADE_FOLDER}"

# Source installer variables and functions
COMMON=$(dirname $0)"/common"
if [ -r "${COMMON}" ]; then
    . "${COMMON}"
fi


# Source package specific variables and functions
SVC_SETUP=$(dirname $0)"/service-setup"
if [ -r "${SVC_SETUP}" ]; then
    . "${SVC_SETUP}"
fi


# Load (wizard) variables stored by postinst
load_variables_from_file ${INST_VARIABLES}

# init variables either from ${INST_VARIABLES}, from package or from wizard
call_func "initialize_variables" install_log



postupgrade ()
{
    log_step "postupgrade"

    call_func "service_restore" install_log


    if [ -d "${TRIM_PKGVAR}/config" ]; then
        $RM "${TRIM_APPDEST}/conf" 2>&1 | install_log
        $LN "${TRIM_PKGVAR}/config" "${TRIM_APPDEST}/conf" 2>&1 | install_log
    fi

    # Add a password string if the default password has not been changed
    if ! grep -q "Password_PBKDF2" "${QBIT_CONF}"; then
        sed -i '/WebUI\\Port/i\WebUI\\Password_PBKDF2=\"@ByteArray(xK2EwRvfGtxfF+Ot9v4WYQ==:bNStY\/6mFYYW8m\/Xm4xSbBjoR2tZNsLZ4KvdUzyCLEOg7tfpchVJucIK9Dwcp6Xe9DI4RwpoCPI9zhicTdtf5A==)\"' ${QBIT_CONF}
        echo "请及时修改默认密码！Change default password NOW！！！<br/>"
        echo "请及时修改默认密码！Change default password NOW！！！<br/>"
        echo "请及时修改默认密码！Change default password NOW！！！"
    fi

    exit 0
}
