#!/bin/bash

# Default display name

SERVICE_COMMAND="${SYNOPKG_PKGDEST}/bin/aliyundrive-subscribe"
#执行用户
USER="aliyundrive-subscribe"

#切换执行用户
EFF_USER="aliyundrive-subscribe"

# Source package specific variable and functions
COMMON=$(dirname $0)"/common"
if [ -r "${COMMON}" ]; then
    . "${COMMON}"
fi

SVC_SETUP=$(dirname $0)"/service-setup"
if [ -r "${SVC_SETUP}" ]; then
    . "${SVC_SETUP}"
fi




case $1 in
    start)
        if daemon_status; then
            echo "${DNAME} is already running" >> ${LOG_FILE}
            exit 0
        else
            echo "Starting ${DNAME} ..." >> ${LOG_FILE}
            start_daemon
            exit $?
        fi
        ;;
    stop)
        if daemon_status; then
            echo "Stopping ${DNAME} ..." >> ${LOG_FILE}
            stop_daemon
            exit $?
        else
            echo "${DNAME} is not running" >> ${LOG_FILE}
            exit 0
        fi
        ;;
    status)
        if daemon_status; then
            echo "${DNAME} is running"
            exit 0
        else
            echo "${DNAME} is not running"
            exit 3
        fi
        ;;
    *)
        exit 1
        ;;
esac

